### ISSUE TITLE
Enemy path finding

### ISSUE THREAD

**Issue by TheManInMyHead** [TNTftw21/RPG#1]
When spawning an enemy on one map  then going to the next and spawning an enemy on that map causes the enemy to not move. the only fix currently is to refresh the game and spawn in the enemy and staying on that map. so if you want enemies they can only be on one map.

**Comment by TNTftw21** [comment]
Problem: Although the `entities` array was being cleared, the entities ID counter was not.

Solution: In the Map.load() function, at the bottom, add `mostRecentId = 0`.

**Comment by TNTftw21** [comment]
Solution confirmed, bug fix incoming.
